### ISSUE TITLE
Make a gradle that automatically gets kotlin version based on spotlin version

### ISSUE THREAD

**Issue by kinggoesgaming** [pxlpowered/spotlin#1]
This way gradle users will have to do something like:

```groovy
plugins {
    id 'plugin` version `spotlinversion`
}
```

and the rest of the kotlin dependency automatically happens.

what say you @pie-flavor?

**Comment by pie-flavor** [comment]
I dunno. I don't actually know how to make Gradle plugins. My only attempt was basically a template plus the equivalent of an #include.

**Comment by kinggoesgaming** [comment]
I can play around... and see how it goes... if its fine enough we can have a separate project that handles that

**Comment by kinggoesgaming** [comment]
Closed for now
