### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by kinggoesgaming** [pxlpowered/spotlin#4]
I am moving away from everything (well almost everything) Minecraft, and such won't be updating this. If you want to take over, comment here and we can proceed from there.

**Comment by pie-flavor** [comment]
hello I am also in this organization

**Comment by kinggoesgaming** [comment]
psss... I forgot... you want to take over? @pie-flavor?

**Comment by kinggoesgaming** [comment]
Closing this
